"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(DEBUG=(bool, False), ALLOWED_HOSTS=(list, []))

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    # django internals
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3rd party apps
    "corsheaders",
    "silk",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "drf_spectacular",
    "service_objects",
    "anymail",
    "django_celery_beat",
    # my apps
    "channels",
    "apps.shared",
    "apps.users",
    "apps.projects",
    "apps.tasks",
    "apps.comments",
    "apps.organization",
    "apps.department",
]

# Custom User Model
AUTH_USER_MODEL = "users.User"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


# Default Auto Field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "silk.middleware.SilkyMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Allow the Vite React frontend during local development
CORS_ALLOWED_ORIGINS = [
    "https://task-manager-tau-six-97.vercel.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "config.asgi.application"

# Redis & Channel Layers
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}



# Database Configuration using DATABASE_URL from .env
DATABASES = {
    "default": env.db("DATABASE_URL"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
LOGIN_URL = "/djadmin/login/"


# Spectacular docs: https://drf-spectacular.readthedocs.io/en/latest/readme.html#installation
SPECTACULAR_SETTINGS = {
    "TITLE": "Task Manager API",
    "DESCRIPTION": "API for managing organizations, departments, projects, tasks, and comments.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
# Django Silk Configuration
# Profiling and introspection tool for Django
SILKY_AUTHENTICATION = True  # Require authentication to access Silk
SILKY_AUTHORIZATION = True  # Require staff/superuser to access Silk profiling
SILKY_INTERCEPT = True  # Profile requests
SILKY_MAX_RECORDS = 10000  # Maximum number of recorded requests to keep
SILKY_MAX_REQUEST_VARS = 1000  # Maximum number of request variables to store
SILKY_MAX_QUERY_SIZE = 0  # Maximum SQL query length (0 = unlimited)
SILKY_PYTHON_SQL_EXPLAIN = False  # Whether to run EXPLAIN on SQL queries
SILKY_JS_FETCH_DEPS = True  # Fetch JS dependencies for charts

from django.urls import reverse_lazy

# Unfold Theme & Administration Settings
UNFOLD = {
    "SITE_TITLE": "Task Manager Admin",
    "SITE_HEADER": "Task Manager Workspace",
    "SITE_URL": "/",
    "SITE_SYMBOL": "task_alt",
    "SHOW_HISTORY": True,
    "SHOW_LANGUAGES": False,
    "ENVIRONMENT": "Task Manager Dev Environment",
    "DASHBOARD_CALLBACK": "config.admin_dashboard.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "238 242 255",
            "100": "224 231 255",
            "200": "199 210 254",
            "300": "165 180 252",
            "400": "129 140 248",
            "500": "99 102 241",
            "600": "79 70 229",
            "700": "67 56 202",
            "800": "55 48 163",
            "900": "49 46 129",
            "950": "30 27 75",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Main Workspace",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Tasks",
                        "icon": "task",
                        "link": reverse_lazy("admin:tasks_task_changelist"),
                        "badge": "config.admin_dashboard.badge_tasks_count",
                    },
                    {
                        "title": "Projects",
                        "icon": "folder",
                        "link": reverse_lazy("admin:projects_project_changelist"),
                        "badge": "config.admin_dashboard.badge_projects_count",
                    },
                ],
            },
            {
                "title": "Organization & Departments",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Organizations",
                        "icon": "corporate_fare",
                        "link": reverse_lazy(
                            "admin:organization_organization_changelist"
                        ),
                    },
                    {
                        "title": "Departments",
                        "icon": "domain",
                        "link": reverse_lazy("admin:department_department_changelist"),
                    },
                ],
            },
            {
                "title": "Users & Access Control",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:users_user_changelist"),
                        "badge": "config.admin_dashboard.badge_users_count",
                    },
                    {
                        "title": "Groups & Permissions",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": "Discussions & Audits",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Comments",
                        "icon": "chat",
                        "link": reverse_lazy("admin:comments_comment_changelist"),
                    },
                ],
            },
        ],
    },
    "HEADER_LINKS": [
        {
            "title": "Swagger Docs",
            "icon": "api",
            "link": reverse_lazy("swagger-ui"),
            "attrs": {"target": "_blank"},
        },
        {
            "title": "ReDoc",
            "icon": "description",
            "link": reverse_lazy("redoc"),
            "attrs": {"target": "_blank"},
        },
        {
            "title": "Silk Profiler",
            "icon": "monitoring",
            "link": "/silk/",
            "attrs": {"target": "_blank"},
        },
    ],
}

# -----------------------------------------------------------------------------
# Celery Configuration
# -----------------------------------------------------------------------------
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# -----------------------------------------------------------------------------
# Celery Beat Schedule Configuration
# -----------------------------------------------------------------------------
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "daily-productivity-summary": {
        "task": "apps.shared.tasks.send_daily_productivity_summary_task",
        # "schedule": crontab(hour=0, minute=0),
        "schedule": crontab(minute="*"),
    },
}

# -----------------------------------------------------------------------------
# Flower Configuration
# -----------------------------------------------------------------------------
CELERY_FLOWER_HOST = env("CELERY_FLOWER_HOST", default="127.0.0.1")
CELERY_FLOWER_PORT = env.int("CELERY_FLOWER_PORT", default=5555)

# -----------------------------------------------------------------------------
# Anymail & Resend Email Configuration
# -----------------------------------------------------------------------------
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
RESEND_API_KEY = env("RESEND_API_KEY", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="onboarding@resend.dev")

ANYMAIL = {
    "RESEND_API_KEY": RESEND_API_KEY,
}

# Run Celery tasks immediately in-memory without needing a Redis broker [2]
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True