# Generated by Django 6.0.6 on 2026-10-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="actual_behavior",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="environment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="expected_behavior",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="issue_type",
            field=models.CharField(
                choices=[("TASK", "Task"), ("BUG", "Bug / Defect")],
                default="TASK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CRITICAL", "Critical"),
                    ("MAJOR", "Major"),
                    ("MINOR", "Minor"),
                    ("TRIVIAL", "Trivial"),
                ],
                default="MINOR",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="steps_to_reproduce",
            field=models.TextField(blank=True, null=True),
        ),
    ]
