import json
import os
from dotenv import load_dotenv
from openai import OpenAI
import pytest
import requests

# 1. Load environment variables
load_dotenv()

BASE_URL = os.getenv("TASK_MANAGER_BASE_URL", "http://127.0.0.1:8000")
API_BASE_URL = f"{BASE_URL}/api"
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5173")

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
BOT_TOKEN = os.getenv("QA_BOT_TOKEN")

# Initialize OpenAI client pointing to Groq
client = (
    OpenAI(
        base_url="https://api.groq.com/openai/v1",
        api_key=GROQ_API_KEY,
    )
    if GROQ_API_KEY
    else None
)

def _get_active_bot_token() -> str | None:
    """Always fetches a live, valid token for super@example.com."""
    global BOT_TOKEN
    
    # Authenticate directly to guarantee a valid token [2]
    for endpoint in [
        f"{API_BASE_URL}/users/auth/login/",
        f"{API_BASE_URL}/users/login/",
    ]:
        try:
            res = requests.post(
                endpoint,
                json={"email": "super@example.com", "password": "super@123"},
                timeout=10,
            )
            if res.status_code == 200:
                data = res.json()
                BOT_TOKEN = data.get("token") or data.get("access")
                return BOT_TOKEN
        except requests.RequestException:
            continue
            
    return BOT_TOKEN


@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """
    Pytest hook that intercepts test failures during execution ('call')
    and auto-files a defect ticket with AI triage into Task Manager.
    """
    outcome = yield
    report = outcome.get_result()

    if report.when == "call" and report.failed:
        test_name = item.name
        error_trace = (
            str(call.excinfo.value) if call.excinfo else "No error trace captured"
        )

        print(
            f"\n[QA Sentinel] Test failed: '{test_name}'. Initiating AI defect triage..."
        )

        # 1. Capture Playwright screenshot if a browser page fixture was used
        page = item.funcargs.get("page", None)
        if page:
            reports_dir = os.path.join(
                os.path.dirname(__file__), "reports", "screenshots"
            )
            os.makedirs(reports_dir, exist_ok=True)
            screenshot_path = os.path.join(reports_dir, f"{test_name}.png")
            try:
                page.screenshot(path=screenshot_path)
                print(f"[QA Sentinel] Screenshot captured at: {screenshot_path}")
            except Exception as e:
                print(f"[QA Sentinel] Could not capture screenshot: {e}")

        # 2. Structure defect with Groq LLM (dynamic model auto-selection)
        prompt = f"""
You are an automated QA triage engineer. A test has failed in our application.

Test Name: {test_name}
Error Details:
\"\"\"
{error_trace}
\"\"\"

Produce a structured bug ticket in JSON format with these exact keys:
- title: Short, actionable defect summary (under 80 chars)
- severity: One of ['CRITICAL', 'MAJOR', 'MINOR', 'TRIVIAL']
- priority: One of ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']
- steps_to_reproduce: Clear numbered steps explaining what the test did
- expected_behavior: What the test expected
- actual_behavior: What actually occurred based on the failure
"""

        bug_data = None
        if client and GROQ_API_KEY:
            try:
                # Query Groq to see which models are actually available to your key
                models_data = client.models.list().data
                active_models = [
                    m.id
                    for m in models_data
                    if not any(
                        k in m.id for k in ["whisper", "guard", "safeguard", "embed"]
                    )
                ]
                selected_model = (
                    active_models[0] if active_models else "llama3-8b-8192"
                )
                print(f"[QA Sentinel] Using active Groq model: '{selected_model}'")

                response = client.chat.completions.create(
                    model=selected_model,
                    response_format={"type": "json_object"},
                    messages=[
                        {
                            "role": "system",
                            "content": "You are a senior SDET analyzing test failure logs. Always return valid JSON.",
                        },
                        {"role": "user", "content": prompt},
                    ],
                )
                bug_data = json.loads(response.choices[0].message.content)
                print(
                    f"[QA Sentinel] AI triage generated by {selected_model} successfully!"
                )
            except Exception as ai_err:
                print(
                    f"[QA Sentinel] Groq API call failed: {ai_err}. Using rule-based fallback..."
                )

        # Fallback if Groq call fails
        if not bug_data:
            bug_data = {
                "title": f"Assertion failure in {test_name}",
                "severity": "CRITICAL" if "assert" in error_trace.lower() else "MAJOR",
                "priority": "HIGH",
                "steps_to_reproduce": f"1. Run test '{test_name}'.\n2. Trigger assertion.\n3. Error trace:\n{error_trace[:200]}",
                "expected_behavior": "Assertion passes without exception.",
                "actual_behavior": error_trace[:300],
            }

        # 3. Retrieve token and file bug ticket via REST API
        token = _get_active_bot_token()
        if not token:
            print(
                "[QA Sentinel] Could not obtain authentication token. Skipping auto-filing."
            )
            return
        # Convert list to string if the LLM returned a JSON array
        steps = bug_data.get("steps_to_reproduce", error_trace)
        if isinstance(steps, list):
            steps = "\n".join(str(s) for s in steps)
        elif not isinstance(steps, str):
            steps = str(steps)

        expected = bug_data.get("expected_behavior", "")
        if isinstance(expected, list):
            expected = "\n".join(str(e) for e in expected)
        elif not isinstance(expected, str):
            expected = str(expected)

        actual = bug_data.get("actual_behavior", error_trace)
        if isinstance(actual, list):
            actual = "\n".join(str(a) for a in actual)
        elif not isinstance(actual, str):
            actual = str(actual)

        payload = {
            "project": 1,
            "title": f"[AUTO-QA] {bug_data.get('title', test_name)}",
            "issue_type": "BUG",
            "severity": bug_data.get("severity", "MAJOR"),
            "priority": bug_data.get("priority", "HIGH"),
            "status": "TODO",
            "steps_to_reproduce": steps,
            "expected_behavior": expected,
            "actual_behavior": actual,
            "environment": "Pytest / Playwright Automated Test Runner",
        }

        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Token {token}",
        }

        try:
            res = requests.post(f"{API_BASE_URL}/tasks/", json=payload, headers=headers)
            if res.status_code == 201:
                created_task = res.json()
                print(
                    f"[QA Sentinel] Successfully auto-filed defect: Task #{created_task.get('id')} - {payload['title']}"
                )
            else:
                print(
                    f"[QA Sentinel] Failed to file defect. HTTP {res.status_code}: {res.text}"
                )
        except Exception as post_err:
            print(f"[QA Sentinel] Could not connect to Task Manager API: {post_err}")


# ==========================================
# PYTEST FIXTURES
# ==========================================


@pytest.fixture(scope="session")
def api_base_url():
    return API_BASE_URL


@pytest.fixture(scope="session")
def frontend_base_url():
    return FRONTEND_BASE_URL


@pytest.fixture(scope="session")
def auth_token():
    token = _get_active_bot_token()
    assert token, "Failed to authenticate test user with backend API."
    return token


@pytest.fixture
def auth_headers(auth_token):
    return {
        "Content-Type": "application/json",
        "Authorization": f"Token {auth_token}",
    }